default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gachamons_backend_development
  host: localhost
  port: 5432
  user: postgres
  password: postgres

test:
  <<: *default
  database: gachamons_backend_test
  port: 5432
  user: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV['MY_APP_DATABASE_URL'] %>
